version: '3.7'

services:
  web:
    depends_on: 
      - mongodb
    build:
      context: .
      dockerfile: Dockerfile
    image: luqmansen/hanako-express
    container_name: hanako-express
    environment: 
      - PORT=3000
      - MONGODB_URI=mongodb://root:root@mongodb:27017/hanako
    ports: 
      - 3000:3000

  mongodb:
    image: mongo:3.6.18-xenial
    container_name: hanako-mongodb
    command: [--auth]
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - 27017:27017
    volumes:
        - hanako-mongodb:/data/db

volumes:
  hanako-mongodb:   

